### ISSUE TITLE
on build, styled-components and typescript breaks on `defaultProps` after yarn upgrade

### ISSUE THREAD

**Issue by usrrname** [rangle/radius#101]
Hello all, new to Rangle but exploring radius for an upcoming project. 

I noticed that when I try to start a newly cloned ds package with yarn start I'll get the following complaint, especially if I attempt to upgrade the dependencies to newer versions of Storybook. I have since downgraded. 

```
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.

✖ Failed to compile
(typescript) Error: /Users/jenc/radius-test/packages/ds/src/components/grid/grid.tsx(22,21): semantic error TS2615: Type of property 'defaultProps' circularly references itself in mapped type 'Pick<ForwardRefExoticComponent<Pick<Pick<any, Exclude<keyof ReactDefaultizedProps<StyledComponentInnerComponent<WithC>, ComponentPropsWithRef<StyledComponentInnerComponent<WithC>>>, StyledComponentInnerAttrs<...> | ... 1 more ... | StyledComponentInnerAttrs<...>> | Exclude<...> | Exclude<...> | Exclude<...>> & Parti...'.
Error: /Users/jenc/radius-test/packages/ds/src/components/grid/grid.tsx(22,21): semantic error TS2615: Type of property 'defaultProps' circularly references itself in mapped type 'Pick<ForwardRefExoticComponent<Pick<Pick<any, Exclude<keyof ReactDefaultizedProps<StyledComponentInnerComponent<WithC>, ComponentPropsWithRef<StyledComponentInnerComponent<WithC>>>, StyledComponentInnerAttrs<...> | ... 1 more ... | StyledComponentInnerAttrs<...>> | Exclude<...> | Exclude<...> | Exclude<...>> & Parti...'.
    at error (/Users/jenc/radius-test/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at throwPluginError (/Users/jenc/radius-test/node_modules/rollup/dist/shared/node-entry.js:11878:12)
    at Object.error (/Users/jenc/radius-test/node_modules/rollup/dist/shared/node-entry.js:12912:24)
    at Object.error (/Users/jenc/radius-test/node_modules/rollup/dist/shared/node-entry.js:12081:38)
    at RollupContext.error (/Users/jenc/radius-test/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:17194:30)
    at /Users/jenc/radius-test/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24958:23
    at arrayEach (/Users/jenc/radius-test/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:534:11)
    at forEach (/Users/jenc/radius-test/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:9360:14)
    at printDiagnostics (/Users/jenc/radius-test/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24931:5)
    at Object.transform (/Users/jenc/radius-test/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:27374:17)
```

Reproduction:
1.  Clone the project by using `git clone --depth=1 https://github.com/rangle/rangle-design-system.git my-tester-ds` and cd into the directory.
2. `yarn` to install all dependencies
3. `yarn upgrade` <-- perhaps an incorrect step to take despite noticing some dependencies are old
2. `cd packages/ds`
1.  run `yarn start`, which calls `tsdx watch`.

In fact, the same behaviour happens on `yarn workspace ds build`. 

Inspecting the complaining line on the file property:
<img width="948" alt="Screen Shot 2021-05-24 at 11 31 38 AM" src="https://user-images.githubusercontent.com/6406037/119370741-9f0b7d00-bc83-11eb-8888-9669dce8a283.png">

```
Type of property 'defaultProps' circularly references itself in mapped type 'ForwardRefExoticBase<Omit<Omit<any, StyledComponentInnerAttrs<WithC> | StyledComponentInnerAttrs<WithC> | StyledComponentInnerAttrs<WithC>> & Partial<...>, "theme"> & { ...; } & WithChildrenIfReactComponentClass<...>>' 
```
I've seen this error appear on `aspect-image.tsx` line 29 as well.

This issue has been discussed here: https://github.com/microsoft/TypeScript/issues/37597 

This error is more of a hinderance to future development, but storybook still builds, locally.

### UPDATE
Upgrading  `@types/styled-components` to  `5.1.7` will resolving this issue.

**Comment by usrrname** [comment]
Issue closed as the most recent updates to main got over that!
